//! `forge demo-project`
//!
//! Creates a tiny demo project with one file per media type and actually runs
//! init, add, commit, and push --mirror all-free end-to-end.
//! The output is a local sample project that can be pushed to configured mirrors.
use anyhow::{Context, Result};
use std::fs;

use crate::cli;

pub fn run() -> Result<()> {
    let tmp = std::env::temp_dir().join("forge-demo-project");
    if tmp.exists() {
        fs::remove_dir_all(&tmp)
            .with_context(|| format!("clear existing demo directory {}", tmp.display()))?;
    }
    fs::create_dir_all(&tmp)?;

    fs::write(
        tmp.join("sample_fight_scene.mp4"),
        b"\x00\x00\x00\x18ftypmp42",
    )?;
    fs::write(tmp.join("thumbnail.png"), b"\x89PNG\r\n\x1a\n")?;
    fs::write(tmp.join("soundtrack.mp3"), b"ID3")?;
    fs::write(tmp.join("character_rig.glb"), b"glTF")?;
    fs::write(
        tmp.join("README.md"),
        b"# Forge Demo Project\n\nGenerated by `forge demo-project`.\n",
    )?;

    println!();
    println!("  forge demo-project - sample media repository");
    println!("  --------------------------------------------");
    println!("  Location: {}", tmp.display());
    println!();
    println!("  Files:");
    println!("    sample_fight_scene.mp4 -> YouTube (private, unlimited)");
    println!("    thumbnail.png          -> Pinterest (secret pin)");
    println!("    soundtrack.mp3         -> SoundCloud (private track)");
    println!("    character_rig.glb      -> Sketchfab (private model)");
    println!("    README.md              -> GitHub (private repo)");
    println!();

    std::env::set_current_dir(&tmp).context("cd into demo dir")?;

    println!("  --- forge init . ---");
    cli::init::run(".")?;
    println!();

    println!("  --- forge add . ---");
    let paths = vec![".".to_string()];
    cli::add::run(&paths, false)?;
    println!();

    println!("  --- forge commit -m \"media sample scene\" ---");
    cli::commit::run("media sample scene")?;
    println!();

    println!("  --- forge push --mirror all-free ---");
    match cli::push::run("origin", Some("all-free"), false) {
        Ok(()) => {}
        Err(e) => {
            eprintln!("  Push did not complete: {e}");
            println!();
            println!("  No backends authenticated? Run these first:");
            println!("    forge auth youtube");
            println!("    forge auth pinterest");
            println!("    forge auth soundcloud");
            println!("    forge auth sketchfab");
            println!("    forge auth github");
            println!(
                "  Then re-run: cd \"{}\" && forge push --mirror all-free",
                tmp.display()
            );
        }
    }

    println!();
    println!("  Demo project ready.");
    println!();

    Ok(())
}
